Repository SpartaChillguys/task-flow, pull requests merged in 2025-09, with the labels that each got.

#2 chore/basic: ci test
  .github/workflows/ci.yml
  .gitignore
  build.gradle
  ci-test
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: chore🧹

#3 chore/basic: 초기 세팅 중
  .github/workflows/ci.yml
Labels: chore🧹

#11 chore/basic: 공통 응답 및 커스텀 예외 처리 추가/수정
  src/main/java/min/taskflow/common/exception/CommonErrorCode.java
  src/main/java/min/taskflow/common/exception/ErrorCode.java
  src/main/java/min/taskflow/common/exception/GlobalException.java
  src/main/java/min/taskflow/common/exception/GlobalExceptionHandler.java
  src/main/java/min/taskflow/common/response/ApiPageResponse.java
  src/main/java/min/taskflow/common/response/ApiResponse.java
  src/main/java/min/taskflow/task/controllder/TaskController.java
  src/main/java/min/taskflow/task/exception/TaskErrorCode.java
  src/main/java/min/taskflow/task/exception/TaskException.java
  src/main/java/min/taskflow/task/service/ExternalTaskService.java
Labels: feature🚀

#13 Feat/user signup
  .gitignore
  build.gradle
  src/main/java/min/taskflow/auth/controller/AuthController.java
  src/main/java/min/taskflow/auth/dto/SignupRequest.java
  src/main/java/min/taskflow/auth/dto/SignupResponse.java
  src/main/java/min/taskflow/auth/service/ExternalAuthService.java
  src/main/java/min/taskflow/auth/service/InternalAuthService.java
  src/main/java/min/taskflow/common/response/ApiResponse.java
  src/main/java/min/taskflow/user/PasswordEncoder.java
  src/main/java/min/taskflow/user/controller/UserController.java
  src/main/java/min/taskflow/user/entity/User.java
  src/main/java/min/taskflow/user/enums/UserRole.java
  src/main/java/min/taskflow/user/exception/UserErrorCode.java
  src/main/java/min/taskflow/user/exception/UserException.java
  src/main/java/min/taskflow/user/mapper/UserMapper.java
  src/main/java/min/taskflow/user/repository/UserRepository.java
  src/main/java/min/taskflow/user/service/ExternalUserService.java
  src/main/java/min/taskflow/user/service/InternalUserService.java
  src/main/resources/application-test.yml
  src/test/java/min/taskflow/user/UserServiceTest.java
Labels: feature🚀

#15 Feat/auth signin
  .github/workflows/ci.yml
  build.gradle
  src/main/java/min/taskflow/auth/config/AuthArgumentResolver.java
  src/main/java/min/taskflow/auth/config/FilterConfig.java
  src/main/java/min/taskflow/auth/config/JwtFilter.java
  src/main/java/min/taskflow/auth/config/JwtUtil.java
  src/main/java/min/taskflow/auth/controller/AuthController.java
  src/main/java/min/taskflow/auth/dto/SignupResponse.java
  src/main/java/min/taskflow/auth/dto/request/LoginRequest.java
  src/main/java/min/taskflow/auth/dto/request/RegisterRequest.java
  src/main/java/min/taskflow/auth/dto/response/LoginResponse.java
  src/main/java/min/taskflow/auth/dto/response/RegisterResponse.java
  src/main/java/min/taskflow/auth/service/ExternalAuthService.java
  src/main/java/min/taskflow/common/annotation/Auth.java
  src/main/java/min/taskflow/common/config/SecurityConfig.java
  src/main/java/min/taskflow/common/config/WebConfig.java
  src/main/java/min/taskflow/common/dto/AuthUser.java
  src/main/java/min/taskflow/user/dto/response/UserResponse.java
  src/main/java/min/taskflow/user/exception/UserErrorCode.java
  src/main/java/min/taskflow/user/mapper/UserMapper.java
  src/main/java/min/taskflow/user/repository/UserRepository.java
  src/main/java/min/taskflow/user/service/InternalUserService.java
  src/test/java/min/taskflow/auth/JwtUtilTest.java
  src/test/java/min/taskflow/auth/LoginTest.java
  src/test/java/min/taskflow/user/RegisterTest.java
  src/test/resources/application-test.yml
Labels: feature🚀

#25 refactor/user: 코드 리팩터링
  src/main/java/min/taskflow/auth/service/ExternalAuthService.java
  src/main/java/min/taskflow/common/config/SecurityConfig.java
  src/main/java/min/taskflow/user/mapper/UserMapper.java
  src/main/java/min/taskflow/user/service/InternalUserService.java
  src/test/java/min/taskflow/user/RegisterTest.java
Labels: refactor🔨

#18 Feat/team : Team CRUD
  src/main/java/min/taskflow/common/exception/ErrorCode.java
  src/main/java/min/taskflow/team/controller/TeamController.java
  src/main/java/min/taskflow/team/dto/MemberResponse.java
  src/main/java/min/taskflow/team/dto/TeamCreateRequest.java
  src/main/java/min/taskflow/team/dto/TeamResponse.java
  src/main/java/min/taskflow/team/dto/TeamUpdateRequest.java
  src/main/java/min/taskflow/team/entity/Team.java
  src/main/java/min/taskflow/team/exception/TeamErrorCode.java
  src/main/java/min/taskflow/team/exception/TeamException.java
  src/main/java/min/taskflow/team/mapper/TeamMapper.java
  src/main/java/min/taskflow/team/repository/TeamRepository.java
  src/main/java/min/taskflow/team/service/TeamService.java
  src/main/resources/application-local.yml
  src/test/java/min/taskflow/team/TeamServiceTest.java
Labels: feature🚀

#30 feat/comment: 댓글 생성 API 구현 및 테스트 코드 작성
  src/main/java/min/taskflow/comment/controller/CommentController.java
  src/main/java/min/taskflow/comment/dto/request/CommentRequest.java
  src/main/java/min/taskflow/comment/dto/response/CommentResponse.java
  src/main/java/min/taskflow/comment/entity/Comment.java
  src/main/java/min/taskflow/comment/exception/CommentErrorCode.java
  src/main/java/min/taskflow/comment/exception/CommentException.java
  src/main/java/min/taskflow/comment/mapper/CommentMapper.java
  src/main/java/min/taskflow/comment/repository/CommentRepository.java
  src/main/java/min/taskflow/comment/service/CommentService.java
  src/main/java/min/taskflow/task/entity/Priority.java
  src/main/java/min/taskflow/task/entity/Task.java
  src/main/java/min/taskflow/task/entity/TaskStatus.java
  src/main/java/min/taskflow/task/repository/TaskRepository.java
  src/main/java/min/taskflow/task/service/InternalTaskService.java
  src/test/java/min/taskflow/comment/CommentServiceTest.java
  src/test/java/min/taskflow/fixture/CommentFixture.java
  src/test/java/min/taskflow/fixture/TaskFixture.java
  src/test/java/min/taskflow/fixture/UserFixture.java
Labels: feature🚀

#34 feat/user: myprofile기능
  src/main/java/min/taskflow/auth/controller/AuthController.java
  src/main/java/min/taskflow/comment/mapper/CommentMapper.java
  src/main/java/min/taskflow/comment/service/CommentService.java
  src/main/java/min/taskflow/common/config/SecurityConfig.java
  src/main/java/min/taskflow/user/controller/UserController.java
  src/main/java/min/taskflow/user/dto/response/UserResponse.java
  src/main/java/min/taskflow/user/mapper/UserMapper.java
  src/main/java/min/taskflow/user/repository/UserRepository.java
  src/main/java/min/taskflow/user/service/ExternalUserService.java
  src/main/java/min/taskflow/user/service/queryService/ExternalQuueryUserService.java
  src/main/java/min/taskflow/user/service/queryService/InternalQueryUserService.java
  src/test/java/min/taskflow/comment/CommentServiceTest.java
  src/test/java/min/taskflow/user/UserProfileTest.java
Labels: feature🚀

#38 Feat/user find team is null
  src/main/java/min/taskflow/user/repository/UserRepository.java
  src/main/java/min/taskflow/user/service/queryService/InternalQueryUserService.java
  src/test/java/min/taskflow/auth/RegisterTest.java
  src/test/java/min/taskflow/user/InternalQueryUserServiceTest.java
Labels: feature🚀

#42 feat/user: 요청 받은 메서드들(혹시몰라서 api까지)
  src/main/java/min/taskflow/auth/service/queryService/QueryExternalAuthService.java
  src/main/java/min/taskflow/auth/service/queryService/QueryInternalAuthService.java
  src/main/java/min/taskflow/user/controller/UserController.java
  src/main/java/min/taskflow/user/service/queryService/InternalQueryUserService.java
  src/test/java/min/taskflow/user/InternalQueryUserServiceTest.java
Labels: feature🚀

#49 feat/comment: 댓글 조회 API 구현 및 테스트 코드 작성 (Git 충돌 문제로 다시 올립니다.)
  src/main/java/min/taskflow/comment/controller/CommentController.java
  src/main/java/min/taskflow/comment/dto/response/CommentResponse.java
  src/main/java/min/taskflow/comment/repository/CommentRepository.java
  src/main/java/min/taskflow/comment/service/CommentService.java
  src/main/java/min/taskflow/user/entity/User.java
  src/test/java/min/taskflow/comment/CommentRepositoryTest.java
  src/test/java/min/taskflow/comment/CommentServiceTest.java
  src/test/java/min/taskflow/fixture/CommentFixture.java
  src/test/java/min/taskflow/fixture/TaskFixture.java
  src/test/java/min/taskflow/fixture/TeamFixture.java
  src/test/java/min/taskflow/fixture/UserFixture.java
Labels: feature🚀

#55 refactor/auth: 컨트롤러에서 userId를 받아오는 형식 @Auth -> @AuthenticationPrincia…
  src/main/java/min/taskflow/auth/config/JwtFilter.java
  src/main/java/min/taskflow/auth/controller/AuthController.java
  src/main/java/min/taskflow/auth/dto/request/RegisterRequest.java
  src/main/java/min/taskflow/auth/service/commandService/ExternalCommandAuthService.java
  src/main/java/min/taskflow/user/controller/UserController.java
Labels: refactor🔨

#57 feat/task: CRUD(미완성)
  src/main/java/min/taskflow/comment/service/CommentService.java
  src/main/java/min/taskflow/task/controllder/TaskController.java
  src/main/java/min/taskflow/task/dto/condition/TaskSearchCondition.java
  src/main/java/min/taskflow/task/dto/request/StatusUpdateRequest.java
  src/main/java/min/taskflow/task/dto/request/TaskCreateRequest.java
  src/main/java/min/taskflow/task/dto/request/TaskUpdateRequest.java
  src/main/java/min/taskflow/task/dto/response/TaskResponse.java
  src/main/java/min/taskflow/task/entity/Priority.java
  src/main/java/min/taskflow/task/entity/Status.java
  src/main/java/min/taskflow/task/entity/Task.java
  src/main/java/min/taskflow/task/entity/TaskStatus.java
  src/main/java/min/taskflow/task/exception/TaskErrorCode.java
  src/main/java/min/taskflow/task/mapper/TaskMapper.java
  src/main/java/min/taskflow/task/repository/TaskRepository.java
  src/main/java/min/taskflow/task/service/ExternalTaskService.java
  src/main/java/min/taskflow/task/service/commandService/ExternalCommandTaskService.java
  src/main/java/min/taskflow/task/service/commandService/InternalCommandTaskService.java
  src/main/java/min/taskflow/task/service/queryService/ExternalQueryTaskService.java
  src/main/java/min/taskflow/task/service/queryService/InternalQueryTaskService.java
  src/main/java/min/taskflow/user/dto/response/AssigneeResponse.java
  src/test/java/min/taskflow/comment/CommentServiceTest.java
  src/test/java/min/taskflow/fixture/TaskFixture.java
  src/test/java/min/taskflow/task/TaskServiceTest.java
Labels: feature🚀

#69 refactor/comment: 댓글 도메인 리팩토링
  src/main/java/min/taskflow/comment/controller/CommentController.java
  src/main/java/min/taskflow/comment/repository/CommentRepository.java
  src/main/java/min/taskflow/comment/service/CommentService.java
  src/main/java/min/taskflow/task/service/query/InternalQueryTaskService.java
  src/test/java/min/taskflow/comment/unit/CommentMapperTest.java
  src/test/java/min/taskflow/comment/unit/CommentRepositoryTest.java
  src/test/java/min/taskflow/comment/unit/CommentServiceTest.java
  src/test/java/min/taskflow/fixture/CommentFixture.java
Labels: refactor🔨

#74 fix/task: getTasksByStatusOrQueryOrAssigneeId
  src/main/java/min/taskflow/task/dto/condition/TaskSearchCondition.java
  src/main/java/min/taskflow/task/repository/TaskRepository.java
  src/main/java/min/taskflow/task/service/command/ExternalCommandTaskService.java
  src/main/java/min/taskflow/task/service/query/ExternalQueryTaskService.java
  src/main/java/min/taskflow/task/service/query/InternalQueryTaskService.java
Labels: bug🐞

#77 refactor/auth: 리프레시 토큰 구현 및 인증 관련 리패키징
  src/main/java/min/taskflow/auth/config/AuthArgumentResolver.java
  src/main/java/min/taskflow/auth/config/JwtUtil.java
  src/main/java/min/taskflow/auth/config/PasswordEncoder.java
  src/main/java/min/taskflow/auth/config/SecurityConfig.java
  src/main/java/min/taskflow/auth/controller/AuthController.java
  src/main/java/min/taskflow/auth/dto/info/TokenInfo.java
  src/main/java/min/taskflow/auth/dto/info/UserInfo.java
  src/main/java/min/taskflow/auth/dto/response/LoginResponse.java
  src/main/java/min/taskflow/auth/exception/AuthErrorCode.java
  src/main/java/min/taskflow/auth/exception/AuthException.java
  src/main/java/min/taskflow/auth/jwt/CookieUtil.java
  src/main/java/min/taskflow/auth/jwt/JwtConsts.java
  src/main/java/min/taskflow/auth/jwt/JwtFilter.java
  src/main/java/min/taskflow/auth/jwt/JwtUtil.java
  src/main/java/min/taskflow/auth/service/commandService/ExternalCommandAuthService.java
  src/main/java/min/taskflow/comment/service/CommentService.java
  src/main/java/min/taskflow/common/annotation/Auth.java
  src/main/java/min/taskflow/common/config/WebConfig.java
  src/main/java/min/taskflow/common/dto/AuthUser.java
  src/main/java/min/taskflow/common/entity/BaseEntity.java
  src/main/java/min/taskflow/common/exception/CommonErrorCode.java
  src/main/java/min/taskflow/user/exception/UserErrorCode.java
  src/test/java/min/taskflow/auth/JwtUtilTest.java
  src/test/java/min/taskflow/auth/LoginTest.java
  src/test/java/min/taskflow/auth/RefreshTokenTest.java
  src/test/java/min/taskflow/auth/RegisterTest.java
  src/test/java/min/taskflow/comment/unit/CommentMapperTest.java
  src/test/java/min/taskflow/fixture/CommentFixture.java
  src/test/java/min/taskflow/search/SearchServiceTest.java
  src/test/java/min/taskflow/team/TeamServiceTest.java
Labels: feature🚀, refactor🔨

#81 refactor/comment: 엔티티 생성자 private 설정, Service 세분화
  src/main/java/min/taskflow/auth/controller/AuthController.java
  src/main/java/min/taskflow/auth/service/command/ExternalCommandAuthService.java
  src/main/java/min/taskflow/auth/service/command/InternalCommandAuthService.java
  src/main/java/min/taskflow/auth/service/query/ExternalQueryAuthService.java
  src/main/java/min/taskflow/auth/service/query/InternalQueryAuthService.java
  src/main/java/min/taskflow/auth/service/queryService/ExternalQueryAuthService.java
  src/main/java/min/taskflow/auth/service/queryService/InternalQueryAuthService.java
  src/main/java/min/taskflow/auth/service/queryService/QueryExternalAuthService.java
  src/main/java/min/taskflow/auth/service/queryService/QueryInternalAuthService.java
  src/main/java/min/taskflow/comment/controller/CommentController.java
  src/main/java/min/taskflow/comment/entity/Comment.java
  src/main/java/min/taskflow/comment/service/command/ExternalCommandCommentService.java
  src/main/java/min/taskflow/comment/service/command/InternalCommandCommentService.java
  src/main/java/min/taskflow/comment/service/query/ExternalQueryCommentService.java
  src/main/java/min/taskflow/comment/service/query/InternalQueryCommentService.java
  src/test/java/min/taskflow/auth/LoginTest.java
  src/test/java/min/taskflow/auth/RefreshTokenTest.java
  src/test/java/min/taskflow/auth/RegisterTest.java
  src/test/java/min/taskflow/comment/unit/CommentServiceTest.java
Labels: refactor🔨

#84 Feat/teammember : Null 예외처리
  src/main/java/min/taskflow/team/exception/TeamErrorCode.java
  src/main/java/min/taskflow/team/service/query/InternalQueryTeamService.java
Labels: refactor🔨

#96 fix/dashboard: stats api 수정
  src/main/java/min/taskflow/task/service/query/InternalQueryTaskService.java
Labels: bug🐞

#100 refactor/comment: 댓글 수정 기능 동시성 문제
  README.md
  src/images/chillguy.png
  src/main/java/min/taskflow/comment/entity/Comment.java
  src/main/java/min/taskflow/comment/exception/CommentErrorCode.java
  src/main/java/min/taskflow/comment/service/command/ExternalCommandCommentService.java
  src/test/java/min/taskflow/fixture/UserFixture.java
Labels: refactor🔨
